import { Canvas, useFrame, useLoader, useThree } from "@react-three/fiber";
import { useRef } from "react";
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\models\guitar.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Guitar(props) {
  const { nodes, materials } = useGLTF("./models/guitar.glb");

  const ref = useRef();

  useFrame((state) => {
    // ref.current.rotation.x += 0.01;
    ref.current.rotation.y += 0.01;
    // ref.current.rotation.z += 0.01;
  });
  return (
    <group {...props} dispose={null} ref={ref}>
      <mesh
        geometry={nodes.group1122908907.geometry}
        material={materials.mat12}
      />
      <mesh
        geometry={nodes.group1983323235.geometry}
        material={materials.mat23}
      />
      <mesh
        geometry={nodes.group1407990207.geometry}
        material={materials.mat23}
      />
      <mesh
        geometry={nodes.group2086466501.geometry}
        material={materials.mat23}
      />
      <mesh
        geometry={nodes.group1431985937.geometry}
        material={materials.mat16}
      />
      <mesh
        geometry={nodes.group173112336.geometry}
        material={materials.mat16}
      />
      <mesh
        geometry={nodes.group1384948276.geometry}
        material={materials.mat16}
      />
      <mesh
        geometry={nodes.group787936409.geometry}
        material={materials.mat16}
      />
      <mesh
        geometry={nodes.group1499409560.geometry}
        material={materials.mat16}
      />
      <mesh
        geometry={nodes.group996156578.geometry}
        material={materials.mat16}
      />
      <mesh
        geometry={nodes.group1530181390.geometry}
        material={materials.mat15}
      />
      <mesh
        geometry={nodes.group1684688086.geometry}
        material={materials.mat15}
      />
      <mesh
        geometry={nodes.group95958777.geometry}
        material={materials.mat15}
      />
      <mesh
        geometry={nodes.group1084130680.geometry}
        material={materials.mat15}
      />
      <mesh
        geometry={nodes.group346913186.geometry}
        material={materials.mat15}
      />
      <mesh
        geometry={nodes.group1540101786.geometry}
        material={materials.mat15}
      />
      <mesh
        geometry={nodes.group806144176.geometry}
        material={materials.mat15}
      />
      <mesh
        geometry={nodes.group1030465556.geometry}
        material={materials.mat15}
      />
      <mesh
        geometry={nodes.group2137697932.geometry}
        material={materials.mat15}
      />
      <mesh
        geometry={nodes.group30759875.geometry}
        material={materials.mat15}
      />
      <mesh
        geometry={nodes.group1933570687.geometry}
        material={materials.mat23}
      />
      <mesh
        geometry={nodes.group1580584633.geometry}
        material={materials.mat12}
      />
      <mesh
        geometry={nodes.group1802300754.geometry}
        material={materials.mat12}
      />
      <mesh
        geometry={nodes.group2052888154.geometry}
        material={materials.mat12}
      />
      <mesh
        geometry={nodes.group284527244.geometry}
        material={materials.mat12}
      />
      <mesh
        geometry={nodes.group1499692460.geometry}
        material={materials.mat12}
      />
      <mesh
        geometry={nodes.group1595146862.geometry}
        material={materials.mat12}
      />
    </group>
  );
}

useGLTF.preload("./models/guitar.glb");
