/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\models\Spaceship.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Spaceship(props) {
  const { nodes, materials } = useGLTF("./models/Spaceship.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Spaceship_FinnTheFrog.geometry}
        material={materials.Atlas}
        scale={50}
      />
    </group>
  );
}

useGLTF.preload("./models/Spaceship.glb");
