import React, { useLayoutEffect, useRef } from "react";
import { Canvas, useFrame, useLoader, useThree } from "@react-three/fiber";

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\models\Spaceship.glb 
*/
import { useGLTF } from "@react-three/drei";

export function Spaceship(props) {
  const ref = useRef();

  // Rotation initiale (par exemple, 45° autour de Y et 20° autour de X)
  useLayoutEffect(() => {
    if (ref.current) {
      ref.current.rotation.y = Math.PI / -10; // 45°
      // ref.current.rotation.x = Math.PI / 9; // 20°
    }
  }, []);

  useFrame((state) => {
    // ref.current.rotation.x += 0.01;
    // ref.current.rotation.y += 0.01;
    const t = state.clock.getElapsedTime();

    ref.current.position.x = Math.sin(t) * 1; // amplitude 2
    ref.current.position.y = Math.sin(3 * t) * 0.5; // amplitude 2
  });

  const { nodes, materials } = useGLTF("./models/Spaceship.glb");
  return (
    <group {...props} ref={ref} dispose={null}>
      <mesh
        geometry={nodes.Spaceship_FinnTheFrog.geometry}
        material={materials.Atlas}
        scale={50}
      />
    </group>
  );
}

useGLTF.preload("./models/Spaceship.glb");
