/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\models\Commodore 64.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Commodore(props) {
  const { nodes, materials } = useGLTF("./models/Commodore 64.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes["Node-Mesh"].geometry} material={materials.mat23} />
      <mesh
        geometry={nodes["Node-Mesh_1"].geometry}
        material={materials.mat8}
      />
      <mesh
        geometry={nodes["Node-Mesh_2"].geometry}
        material={materials.mat18}
      />
      <mesh
        geometry={nodes["Node-Mesh_3"].geometry}
        material={materials.mat5}
      />
      <mesh
        geometry={nodes["Node-Mesh_4"].geometry}
        material={materials.mat21}
      />
      <mesh
        geometry={nodes["Node-Mesh_5"].geometry}
        material={materials.mat19}
      />
      <mesh
        geometry={nodes["Node-Mesh_6"].geometry}
        material={materials.mat22}
      />
    </group>
  );
}

useGLTF.preload("./models/Commodore 64.glb");
